### ISSUE TITLE
BigQueryStorageAPI not running on Dataproc

### ISSUE THREAD

**Issue by mauliksoneji** [googleapis/google-cloud-java#6132]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Google cloud dataproc version: 1.4.12-debian9
2. OS type and version: debian9
3. Java version:  OpenJDK 1.8.0_212
4. google-cloud-java version(s): `1.85.0`

#### Steps to reproduce
I am trying to use BigQueryStorageAPI to read data from Bigquery on dataproc. The code example that I have provided works on my local machine, but doesnt work on dataproc.
The code is running well on dataproc if I dont use BigQueryStorageAPI. I am not sure if there is some config missing when using BigQueryStorageAPI

#### Code example

```java
public static void main(String args[]) throws Exception {
        // Sets your Google Cloud Platform project ID.
        String projectId = "YOUR_PROJECT_ID";
        Integer snapshotMillis = null;

        GoogleCredentials credentials;
        String bqSecretFile = "gcp-bq-secret.json";
        File credentialsPath = new File(bqSecretFile);
        try (FileInputStream serviceAccountStream = new FileInputStream(credentialsPath)) {
            credentials = ServiceAccountCredentials.fromStream(serviceAccountStream);
        }
        BigQueryStorageSettings.Builder bigQueryStorageSettings = BigQueryStorageSettings.newBuilder()
                .setCredentialsProvider(FixedCredentialsProvider.create(credentials));
        bigQueryStorageSettings.createReadSessionSettings().getRetrySettings().toBuilder()
                .setInitialRetryDelay(Duration.ofMillis(1L))
                .setRetryDelayMultiplier(1.3)
                .setMaxRetryDelay(Duration.ofMinutes(1L))
                .setInitialRpcTimeout(Duration.ofDays(1L))
                .setRpcTimeoutMultiplier(1.0)
                .setMaxRpcTimeout(Duration.ofDays(1L))
                .setTotalTimeout(Duration.ofDays(1L));


        try (BigQueryStorageClient client = BigQueryStorageClient.create(bigQueryStorageSettings.build())) {
            TableReference tableReference =
                    TableReference.newBuilder()
                            .setProjectId(projectId)
                            .setDatasetId("dataset")
                            .setTableId("table")
                            .build();

            // We specify the columns to be projected by adding them to the selected fields,
            // and set a simple filter to restrict which rows are transmitted.
            TableReadOptions options =
                    TableReadOptions.newBuilder()
                            .setRowRestriction("created_at >= '2019-08-13 08:24:26.789 UTC'")
                            .build();

            String parent = String.format("projects/%s", projectId);
            // Begin building the session request.
            CreateReadSessionRequest.Builder builder =
                    CreateReadSessionRequest.newBuilder()
                            .setParent(parent)
                            .setTableReference(tableReference)
                            .setReadOptions(options)
                            // This API can also deliver data serialized in Apache Arrow format.
                            // This example leverages Apache Avro.
                            .setFormat(DataFormat.AVRO)
                            // We use a LIQUID strategy in this example because we only
                            // read from a single stream.  Consider BALANCED if you're consuming
                            // multiple streams concurrently and want more consistent stream sizes.
                            .setShardingStrategy(Storage.ShardingStrategy.LIQUID)
                            .setRequestedStreams(100);


            // Request the session creation.
            ReadSession session = client.createReadSession(builder.build());
            BigQueryFactory factory = new BigQueryFactory();

            Configuration hadoopConf = new Configuration();
            hadoopConf.set("google.cloud.auth.service.account.enable", "true");
            hadoopConf.set("google.cloud.auth.service.account.json.keyfile", bqSecretFile);
            hadoopConf.set("mapred.bq.auth.service.account.json.keyfile", bqSecretFile);
            hadoopConf.set("fs.gs.auth.service.account.json.keyfile", bqSecretFile);
            BigQueryHelper bigQueryHelper = factory.getBigQueryHelper(hadoopConf);

            com.google.api.services.bigquery.model.TableReference tableReference2 =
                    new com.google.api.services.bigquery.model.TableReference()
                            .setDatasetId("dataset")
                            .setProjectId(projectId)
                            .setTableId("table");
            Table table = bigQueryHelper.getTable(tableReference2);
            long numRows = table.getNumRows().longValue();
            long limit = Math.round(1.5 * numRows / session.getStreamsCount());

            List<DirectBigQueryInputFormat.DirectBigQueryInputSplit> collect = session.getStreamsList().stream()
                    .map(
                            stream ->
                                    new DirectBigQueryInputFormat.DirectBigQueryInputSplit(
                                            stream.getName(), session.getAvroSchema().getSchema(), limit))
                    .collect(Collectors.toList());

            session.getStreamsList().forEach(streamRead -> {
                StreamPosition readPosition =
                        StreamPosition.newBuilder().setStream(streamRead).build();
                ReadRowsRequest readRowsRequest =
                        ReadRowsRequest.newBuilder().setReadPosition(readPosition).build();
                ServerStream<ReadRowsResponse> stream = client.readRowsCallable()
                        .call(readRowsRequest);
                long totalRows = 0;
                for (ReadRowsResponse response : stream) {
                    Preconditions.checkState(response.hasAvroRows());
                    totalRows += response.getAvroRows().getRowCount();
                    System.out.println("Got these many new " + response.getAvroRows().getRowCount() + " " + totalRows); 
                }
                System.out.println(totalRows);
            });
        }
 }
```

#### Stack trace
On enabling DEBUG logging, I see that the OUTBOUND HEADERS request is not sent on dataproc.
```
19/08/21 19:02:34 DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler: [id: 0xecbae4ac, L:/redacted:36816 - R:bigquerystorage.googleapis.com/redacted:443] HANDSHAKEN: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
19/08/21 19:02:34 DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler: [id: 0xecbae4ac, L:/redacted:36816 - R:bigquerystorage.googleapis.com/redacted:443] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
19/08/21 19:02:34 DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler: [id: 0xecbae4ac, L:/redacted:36816 - R:bigquerystorage.googleapis.com/redacted:443] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
19/08/21 19:02:37 DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler: [id: 0xecbae4ac, L:/redacted:36816 - R:bigquerystorage.googleapis.com/redacted:443] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=16384}
19/08/21 19:02:43 DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler: [id: 0xecbae4ac, L:/redacted:36816 - R:bigquerystorage.googleapis.com/redacted:443] OUTBOUND SETTINGS: ack=true
```

After this, the Settings Read OUTPUT HEADERS request is not sent.
I see on my local machine, the following request being sent:
```
16:13:39 DEBUG NettyClientHandler: [id: 0xa51379e5, L:/redacted:49245 - R:bigquerystorage.googleapis.com/redacted:443] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: bigquerystorage.googleapis.com:443, :path: /google.cloud.bigquery.storage.v1beta1.BigQueryStorage/CreateReadSession, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.21.0, x-goog-api-client: gl-java/1.8.0_222 gapic/0.98.0-beta gax/1.47.1 grpc/1.21.0, x-goog-request-params: table_reference.project_id=my_project&table_reference.dataset_id=playground, grpc-accept-encoding: gzip, authorization: Bearer redacted, grpc-timeout: 119536m] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
```

The dataproc job has been running since more than 3 hours and it has not fetched any data from bigquery.
Am I missing some configuration?

Thanks!

**Comment by kmjung** [comment]
Can you transfer this issue to the https://github.com/GoogleCloudPlatform/spark-bigquery-connector repository?

**Comment by athakor** [comment]
@mauliksoneji  can you provide list of dependencies with version which you have used.

**Comment by mauliksoneji** [comment]
Dependencies:
```    compile group: 'org.apache.spark', name: 'spark-core_2.12', version: '2.4.3'
    compile group: 'org.apache.spark', name: 'spark-sql_2.12', version: '2.4.3'
    compile group: 'com.google.cloud.bigdataoss', name: 'bigquery-connector', version: 'hadoop3-1.0.0-RC2'
    compile group: 'com.google.cloud.bigdataoss', name: 'gcs-connector', version: 'hadoop3-2.0.0-RC2'
    compile group: 'com.google.cloud', name: 'google-cloud-bigquery', version: '1.85.0'
    compile group: 'com.google.guava', name: 'guava', version: '28.0-jre'
    compile group: 'org.apache.hadoop', name: 'hadoop-mapreduce-client-core', version: '3.2.0'
    compile group: 'org.apache.hadoop', name: 'hadoop-common', version: '3.2.0'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.9'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.9'
    compile group: 'com.fasterxml.jackson.module', name: 'jackson-module-scala_2.12', version: '2.9.8'
    compile group: 'org.aeonbits.owner', name: 'owner', version: '1.0.10'
    compile group: 'com.google.cloud', name: 'google-cloud-storage', version: '1.88.0'
    compile group: 'org.apache.kafka', name: 'kafka_2.12', version: '2.3.0'```

**Comment by athakor** [comment]
@mauliksoneji I have followed your steps and reproduced the issue which you had face.
The cause of issue is like when you submit job on dataproc cluster bigquery storage api got hang at the create read session time.
```
    BigQueryStorageClient client = BigQueryStorageClient.create(bigQueryStorageSettings.build());
    TableReferenceProto.TableReference tableReference =
        TableReferenceProto.TableReference.newBuilder()
            .setProjectId(projectId)
            .setDatasetId("dataId")
            .setTableId("tableId")
            .build();

      String parent = String.format("projects/%s", projectId);
      Storage.CreateReadSessionRequest.Builder builder =
          Storage.CreateReadSessionRequest.newBuilder()
              .setParent(parent)
              .setTableReference(tableReference)
              .setFormat(Storage.DataFormat.AVRO)
              .setShardingStrategy(Storage.ShardingStrategy.BALANCED)
              .setRequestedStreams(100);

      // Request the session creation.
      Storage.ReadSession session = client.createReadSession(builder.build()); //here getting hang.
      System.out.println("Readsession is created");
```
@shollyman help would be appreciated.

**Comment by eriklincoln** [comment]
I am seeing what might also be the same behavior in Apache Beam using both DirectRunner (with default credentials) and DataflowRunner (using an SA with both BigQuery User and Read Session roles). I am able to use these same credentials from the Python SDK both locally using default credentials and in ML Engine so I do not think this is an authentication problem.

This is the Beam (v2.16) pipeline (Kotlin):

```kotlin
    val p = Pipeline.create(options)
    p.apply("ReadValidationData",
        BigQueryIO.readTableRows()
            .withoutValidation()
            .from(options.userSummaryTableSpec)
            .withMethod(BigQueryIO.TypedRead.Method.DIRECT_READ)
            .withRowRestriction("ml_partition = \"validation\"")
    )
    return p
```

and the exception:

```
Exception in thread "main" java.lang.AbstractMethodError: com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.needsCredentials()Z
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
	at com.google.cloud.bigquery.storage.v1beta1.stub.EnhancedBigQueryStorageStub.create(EnhancedBigQueryStorageStub.java:89)
	at com.google.cloud.bigquery.storage.v1beta1.BigQueryStorageClient.<init>(BigQueryStorageClient.java:144)
	at com.google.cloud.bigquery.storage.v1beta1.BigQueryStorageClient.create(BigQueryStorageClient.java:125)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$StorageClientImpl.<init>(BigQueryServicesImpl.java:1028)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$StorageClientImpl.<init>(BigQueryServicesImpl.java:1011)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl.getStorageClient(BigQueryServicesImpl.java:131)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryStorageSourceBase.split(BigQueryStorageSourceBase.java:142)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryStorageTableSource.split(BigQueryStorageTableSource.java:42)
	at org.apache.beam.runners.direct.BoundedReadEvaluatorFactory$InputProvider.getInitialInputs(BoundedReadEvaluatorFactory.java:214)
	at org.apache.beam.runners.direct.ReadEvaluatorFactory$InputProvider.getInitialInputs(ReadEvaluatorFactory.java:89)
	at org.apache.beam.runners.direct.RootProviderRegistry.getInitialInputs(RootProviderRegistry.java:76)
	at org.apache.beam.runners.direct.ExecutorServiceParallelExecutor.start(ExecutorServiceParallelExecutor.java:155)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:208)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
	at com.ntconcepts.gcpdemo2.predict.MainKt.main(Main.kt:11)
```

**Comment by mauliksoneji** [comment]
You should update gax-grpc library, I saw that version 1.49.0 of this library works.

**Comment by eriklincoln** [comment]
That fixed the problem for Beam, too. Thanks, @mauliksoneji!

**Comment by athakor** [comment]
This seems like resolved

**Comment by mauliksoneji** [comment]
@athakor The issue that @eriklincoln posted is a separate issue. can you please provide some information on what changes you made to run the code that I originally posted.

As per your last comment, you identified an issue; can you please provide some clarity on how this issue has been fixed.

**Comment by lukeman** [comment]
Did this ever get addressed anywhere? I'm still seeing the same behavior.
